# Generated by Django 3.2.7 on 2021-11-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyCandidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('state', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=200)),
                ('degree_level', models.CharField(max_length=10)),
                ('degree_program', models.CharField(max_length=50)),
                ('graduation_date', models.DateField()),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailSubscriberForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
