# Generated by Django 3.2.7 on 2021-11-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyCandidatesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('state', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=200)),
                ('degree_level', models.CharField(max_length=10)),
                ('degree_program', models.CharField(max_length=50)),
                ('graduation_date', models.DateField()),
                ('video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailSubscriberFormModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscriber_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='ApplyCandidates',
        ),
        migrations.DeleteModel(
            name='EmailSubscriberForm',
        ),
    ]
